#!/bin/bash

#/ NAME
#/     add-deb -- Add a deb package to reprepro
#/
#/ SYNOPSIS
#/     add deb DISTRO PACKAGE

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

function main {
  case "$#" in
    0)
      logger_fatal "missing DISTRO, PACKAGE"
      exit 1
      ;;
    1)
      logger_fatal "missing PACKAGE"
      exit 1
      ;;
    *)
      true
      ;;
  esac

  local nm_distro="$1"; shift

  local packages
  while [[ "$#" > 0 ]]; do
    local fqpkg="$(cd -P $(dirname $1) && pwd -P $(dirname $1))/$(basename $1)"
    packages+=($fqpkg)
    shift
  done

  cd $shome/apt
  reprepro -Vb . includedeb "$nm_distro" "${packages[@]}"
}

require sub "$BASH_SOURCE" "$@"
